/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.littleBoat.View;

import java.awt.event.ActionListener;

/**
 *
 * @author usuario
 */
public class NuevoBarco extends javax.swing.JFrame {

    /**
     * Creates new form NuevoBarco
     */
    public NuevoBarco() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        NextBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        IdText = new javax.swing.JTextField();
        IdLabel = new javax.swing.JLabel();
        ShipNameLabel = new javax.swing.JLabel();
        ShipNameText = new javax.swing.JTextField();
        PortNameLabel = new javax.swing.JLabel();
        PortNameText = new javax.swing.JTextField();
        OwnerLabel = new javax.swing.JLabel();
        OwnerComboBox = new javax.swing.JComboBox<>();
        NewOwnerBtn = new javax.swing.JButton();
        ResetBtn = new javax.swing.JButton();
        CancelBtn = new javax.swing.JButton();
        TitleNewShip = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(170, 234, 248));

        NextBtn.setBackground(new java.awt.Color(255, 255, 255));
        NextBtn.setForeground(new java.awt.Color(0, 0, 0));
        NextBtn.setText("Siguiente");
        NextBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextBtnActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(232, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        IdText.setBackground(new java.awt.Color(255, 255, 255));
        IdText.setForeground(new java.awt.Color(0, 0, 0));
        IdText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IdTextActionPerformed(evt);
            }
        });

        IdLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        IdLabel.setForeground(new java.awt.Color(0, 0, 0));
        IdLabel.setText("Matricula :");

        ShipNameLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ShipNameLabel.setForeground(new java.awt.Color(0, 0, 0));
        ShipNameLabel.setText("Nombre del Barco :");

        ShipNameText.setBackground(new java.awt.Color(255, 255, 255));
        ShipNameText.setForeground(new java.awt.Color(0, 0, 0));
        ShipNameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShipNameTextActionPerformed(evt);
            }
        });

        PortNameLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        PortNameLabel.setForeground(new java.awt.Color(0, 0, 0));
        PortNameLabel.setText("Nombre de Capitania de Puerto :");

        PortNameText.setBackground(new java.awt.Color(255, 255, 255));
        PortNameText.setForeground(new java.awt.Color(0, 0, 0));
        PortNameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PortNameTextActionPerformed(evt);
            }
        });

        OwnerLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        OwnerLabel.setForeground(new java.awt.Color(0, 0, 0));
        OwnerLabel.setText("Propetario :");

        OwnerComboBox.setBackground(new java.awt.Color(255, 255, 255));
        OwnerComboBox.setForeground(new java.awt.Color(0, 0, 0));
        OwnerComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        OwnerComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OwnerComboBoxActionPerformed(evt);
            }
        });

        NewOwnerBtn.setBackground(new java.awt.Color(255, 255, 255));
        NewOwnerBtn.setForeground(new java.awt.Color(0, 0, 0));
        NewOwnerBtn.setText("Nuevo Porpetario");
        NewOwnerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewOwnerBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(IdLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(IdText, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(ShipNameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ShipNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(PortNameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PortNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(OwnerLabel)
                        .addGap(18, 18, 18)
                        .addComponent(OwnerComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(NewOwnerBtn)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IdText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IdLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ShipNameLabel)
                    .addComponent(ShipNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PortNameLabel)
                    .addComponent(PortNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OwnerLabel)
                    .addComponent(OwnerComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NewOwnerBtn))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        ResetBtn.setBackground(new java.awt.Color(255, 255, 255));
        ResetBtn.setForeground(new java.awt.Color(0, 0, 0));
        ResetBtn.setText("Limpiar");
        ResetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetBtnActionPerformed(evt);
            }
        });

        CancelBtn.setBackground(new java.awt.Color(255, 255, 255));
        CancelBtn.setForeground(new java.awt.Color(0, 0, 0));
        CancelBtn.setText("Cancelar");
        CancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelBtnActionPerformed(evt);
            }
        });

        TitleNewShip.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        TitleNewShip.setForeground(new java.awt.Color(0, 0, 0));
        TitleNewShip.setText("Nuevo Barco");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(CancelBtn)
                        .addGap(107, 107, 107)
                        .addComponent(ResetBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(NextBtn)))
                .addGap(25, 25, 25))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(TitleNewShip)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TitleNewShip)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CancelBtn)
                    .addComponent(ResetBtn)
                    .addComponent(NextBtn))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelBtnActionPerformed
        this.dispose();
    }//GEN-LAST:event_CancelBtnActionPerformed

    private void ResetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetBtnActionPerformed
        IdText.setText("");
        ShipNameText.setText("");
        PortNameText.setText("");
        OwnerComboBox.setSelectedIndex(0);
    }//GEN-LAST:event_ResetBtnActionPerformed

    private void NextBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextBtnActionPerformed
        String matricula = IdText.getText();
        String nombreBarco = ShipNameText.getText();
        String nombreCapitania = PortNameText.getText();
        String propietario = OwnerComboBox.getSelectedItem().toString();
    }//GEN-LAST:event_NextBtnActionPerformed

    private void IdTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IdTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IdTextActionPerformed

    private void ShipNameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShipNameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ShipNameTextActionPerformed

    private void PortNameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PortNameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PortNameTextActionPerformed

    private void OwnerComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OwnerComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OwnerComboBoxActionPerformed

    private void NewOwnerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewOwnerBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NewOwnerBtnActionPerformed

    
    public void setCancelButtonListener(ActionListener listener) {
        CancelBtn.addActionListener(listener);
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NuevoBarco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NuevoBarco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NuevoBarco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NuevoBarco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NuevoBarco().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelBtn;
    private javax.swing.JLabel IdLabel;
    private javax.swing.JTextField IdText;
    private javax.swing.JButton NewOwnerBtn;
    private javax.swing.JButton NextBtn;
    private javax.swing.JComboBox<String> OwnerComboBox;
    private javax.swing.JLabel OwnerLabel;
    private javax.swing.JLabel PortNameLabel;
    private javax.swing.JTextField PortNameText;
    private javax.swing.JButton ResetBtn;
    private javax.swing.JLabel ShipNameLabel;
    private javax.swing.JTextField ShipNameText;
    private javax.swing.JLabel TitleNewShip;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
