/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.littleboat.View;

/**
 *
 * @author samux
 */
public class OwnerTableButtons extends javax.swing.JPanel {

    /**
     * Creates new form OwnerListBtnSet
     */
    public OwnerTableButtons() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        owner_GeneratePermitButton = new org.littleboat.View.CustomButton();
        Owner_EditButton = new org.littleboat.View.CustomButton();
        Owner_DeleteButton = new org.littleboat.View.CustomButton();

        owner_GeneratePermitButton.setIcon(new javax.swing.ImageIcon("C:\\Desktop\\Escuela\\ConstruccionSoftware\\Proyecto\\Gestion_Embarcaciones\\src\\main\\java\\org\\littleBoat\\resources\\CertificadeIcon.png")); // NOI18N
        owner_GeneratePermitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                owner_GeneratePermitButtonActionPerformed(evt);
            }
        });

        Owner_EditButton.setIcon(new javax.swing.ImageIcon("C:\\Desktop\\Escuela\\ConstruccionSoftware\\Proyecto\\Gestion_Embarcaciones\\src\\main\\java\\org\\littleBoat\\resources\\EditIcon.png")); // NOI18N

        Owner_DeleteButton.setIcon(new javax.swing.ImageIcon("C:\\Desktop\\Escuela\\ConstruccionSoftware\\Proyecto\\Gestion_Embarcaciones\\src\\main\\java\\org\\littleBoat\\resources\\DeleteIcon.png")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(owner_GeneratePermitButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Owner_EditButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Owner_DeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(owner_GeneratePermitButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Owner_EditButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Owner_DeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void actionButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actionButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_actionButton4ActionPerformed

    private void owner_GeneratePermitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_owner_GeneratePermitButtonActionPerformed
        System.out.println("generar certificado");
    }//GEN-LAST:event_owner_GeneratePermitButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.littleboat.View.CustomButton Owner_DeleteButton;
    private org.littleboat.View.CustomButton Owner_EditButton;
    private org.littleboat.View.CustomButton owner_GeneratePermitButton;
    // End of variables declaration//GEN-END:variables
}
