/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package org.LittleBoat.View;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author samux
 */
public class OwnerTableButtons extends javax.swing.JPanel {

    /**
     * Creates new form OwnerListBtnSet
     */
    public OwnerTableButtons() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        owner_CertificadeButton = new org.LittleBoat.View.CustomButton();
        owner_EditButton = new org.LittleBoat.View.CustomButton();
        owner_DeleteButton = new org.LittleBoat.View.CustomButton();

        owner_CertificadeButton.setIcon(new javax.swing.ImageIcon("C:\\Desktop\\Escuela\\ConstruccionSoftware\\repositorio\\Gestion_Embarcaciones\\src\\main\\resources\\viewIcons\\CertificadeIcon.png")); // NOI18N

        owner_EditButton.setIcon(new javax.swing.ImageIcon("C:\\Desktop\\Escuela\\ConstruccionSoftware\\repositorio\\Gestion_Embarcaciones\\src\\main\\resources\\viewIcons\\EditIcon.png")); // NOI18N

        owner_DeleteButton.setIcon(new javax.swing.ImageIcon("C:\\Desktop\\Escuela\\ConstruccionSoftware\\repositorio\\Gestion_Embarcaciones\\src\\main\\resources\\viewIcons\\DeleteIcon.png")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(owner_CertificadeButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(owner_EditButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(owner_DeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(owner_CertificadeButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(owner_EditButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(owner_DeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void actionButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actionButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_actionButton4ActionPerformed

    private void owner_GeneratePermitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_owner_GeneratePermitButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_owner_GeneratePermitButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.LittleBoat.View.CustomButton owner_CertificadeButton;
    private org.LittleBoat.View.CustomButton owner_DeleteButton;
    private org.LittleBoat.View.CustomButton owner_EditButton;
    // End of variables declaration//GEN-END:variables

    public void initEvent(TableActionEvent  event, int row){
        owner_CertificadeButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent actionEvent){
                event.onCertificadeButton(row);
            }
        });
        owner_EditButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent actionEvent){
                event.onEditButton(row);
            }
        });
        owner_DeleteButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent actionEvent){
                event.onDeleteButton(row);
            }
        });
    }
   // public void setOwner_CertificadeButtonListener(ActionListener listener) {
      //  owner_CertificadeButton.addActionListener(listener);
   // }

   /// public void setOwner_DeleteButtonListener(ActionListener listener) {
      //  owner_DeleteButton.addActionListener(listener);
   // }

   // public void setOwner_EditButtonListener(ActionListener listener) {
    //    owner_EditButton.addActionListener(listener);
   // }
}
